# Generated by Django 4.1.7 on 2023-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processed_image',
            field=models.ImageField(blank=True, upload_to='processed_photos/'),
        ),
    ]
