# Generated by Django 4.1.7 on 2023-10-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_processing', '0002_photo_processed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='processed_image',
        ),
    ]
